name: "Run Anchore Scan Action (ACS SARIF Demo)"
 
on: [push]
 
jobs:
  Anchore-Scan-Action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag localbuild/testimage:latest      
    - name: Run the local anchore scan action itself with sarif generation enabled
      uses: anchore/scan-action@master
      with:
        image-reference: "localbuild/testimage:latest"
        debug: true
        acs-report-enable: true
        acs-report-severity-cutoff: "Medium"
    - name: Upload Anchore Scan ACS Report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
